version: '3.9'

services:
  web:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - mongodb_service
  mongodb_service:
    image: mongo:6
    ports:
      - "5001:5000"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
